### ISSUE TITLE
Feature request: Support Meteor.subscribe

### ISSUE THREAD

**Issue by stubailo** [deanius/meteor-promise#4]
Hi! Great package.

I'd like to be able to use this for subscriptions as well:

```js
Meteor.subscibePromise("myData").then(function () {
  // Now I have my data!
});
```

Basically, it should track the `ready()` handle on the subscription, and fire the promise when the subscription is ready.

**Comment by stubailo** [comment]
Oh, even better - `Meteor.subscribe` already takes a callback, so it should be basically the same as what you have now for methods.

**Comment by chicagogrooves** [comment]
Thanks! As for `Meteor.subscribe` that already (synchronously) returns a handle to the subscription, maybe..

```
   var subHandle = Meteor.subscribe("pub", param);
  //can do subHandle.stop() right away

   //otherwise chain handlers on a Promise
   subHandle.ready().then( stuff ) 

   //or register reactive handlers
   Tracker.autorun( function () { 
       if (subHandle.ready()) {
          console.log('ready')
       }
   });
```

But I don't know - `ready()` would have to return true if already ready, register a reactive dependency if `Tracker.active`, and return a promise (which, as an object, would be truthy), if it were not ready. That may be too much overloading..

With `Meteor.promise`, I wondered if `Meteor.call` could simply provide a promise for the result if the callback is omitted (on the client), instead of having a different method name of `Meteor.promise`. But it gets into how much overloading is too much, you know ? 

Hard questions...

**Comment by stubailo** [comment]
I see the issue - if the function returns a promise instead of a handle, how would you stop the subscription later? Hmm... maybe this calls for a general function to get a promise from a reactive computation:

```js
Tracker.promise(function () {
  return handle.ready() === true;
}).then(function () {
  // do something, the computation is stopped for you automatically!
});
```

**Comment by deanius** [comment]
Closing since it's out of scope for this project (and hopefully this project is obsolete when Meteor 1.2 comes out with better ES6 support)

**Comment by deanius** [comment]
Actually, I just had an idea for this while riding my bike this morning. The object returned by subscribe could have a `readyPromise` field on it! I could patch that object's prototype in this package, or, would you support that being a PR on Meteor core ?

**Comment by stubailo** [comment]
I think a good start will be to just add that method in this package, but I suspect we will promisify this soon anyway as part of the move to ES2015.
